version: "3.7"
services:

  db:
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/quizinit.sql
    networks:
      - tdev-net

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tdev-net

networks:
  tdev-net:
    driver: bridge